// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0ByUV8zzKdSe8p3Ti_JdEym40AgZ_vM',
    appId: '1:474597861126:web:438becd20ecf5ead25e087',
    messagingSenderId: '474597861126',
    projectId: 'staff-attendance-system-396f9',
    authDomain: 'staff-attendance-system-396f9.firebaseapp.com',
    storageBucket: 'staff-attendance-system-396f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmyQNS-M4ikYqAnvXGjZNzP3s8jxUYUCc',
    appId: '1:474597861126:android:8df0e4c5573d162225e087',
    messagingSenderId: '474597861126',
    projectId: 'staff-attendance-system-396f9',
    storageBucket: 'staff-attendance-system-396f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5hLu83kBeqj6kEu0f8v_DuZYhTG_pbhk',
    appId: '1:474597861126:ios:56c089d400c9fc4225e087',
    messagingSenderId: '474597861126',
    projectId: 'staff-attendance-system-396f9',
    storageBucket: 'staff-attendance-system-396f9.firebasestorage.app',
    iosBundleId: 'com.example.staffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5hLu83kBeqj6kEu0f8v_DuZYhTG_pbhk',
    appId: '1:474597861126:ios:56c089d400c9fc4225e087',
    messagingSenderId: '474597861126',
    projectId: 'staff-attendance-system-396f9',
    storageBucket: 'staff-attendance-system-396f9.firebasestorage.app',
    iosBundleId: 'com.example.staffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ0ByUV8zzKdSe8p3Ti_JdEym40AgZ_vM',
    appId: '1:474597861126:web:a22fc1906e01115d25e087',
    messagingSenderId: '474597861126',
    projectId: 'staff-attendance-system-396f9',
    authDomain: 'staff-attendance-system-396f9.firebaseapp.com',
    storageBucket: 'staff-attendance-system-396f9.firebasestorage.app',
  );
}